### ISSUE TITLE
Implement job to recover stale “in progress” workflows

### ISSUE THREAD

**Issue by gabzim** [wormhole-foundation/relayer-engine#20]
If an executor process crashes, its current job won’t automatically be pulled back from the in progress queue. We should have a job that runs every certain “visibility window” to make available for other workers the failed job.

a sorted set using the timestamp as the age of the job would be ideal but it’s not supported by redis atm (bzmove)

**Comment by JoeHowarth** [comment]
Fixed by https://github.com/wormhole-foundation/relayer-engine/pull/39
