### ISSUE TITLE
Custom metrics defined by plugins

### ISSUE THREAD

**Issue by JoeHowarth** [wormhole-foundation/relayer-engine#26]
Builds off #19 (general prometheus style metrics) 

### Problem
Plugin authors may want to track application specific events and emit metrics. (e.g. dollar volume of a token bridge relayer plugin).

### Proposal
Allow the plugin to register metrics during `afterSetup` or in constructor, then update those metrics in `consumeEvent` and `handleWorkflow`

**Comment by gabzim** [comment]
Plugins in the new implementation are able to expose metrics by receiving the registry provided by the engine. I believe the `missedVaa` middleware does this.
