### ISSUE TITLE
Multi-node listener 

### ISSUE THREAD

**Issue by JoeHowarth** [wormhole-foundation/relayer-engine#36]
### Background
The listener can theoretically run multi-node currently but this has never been tested. This is important to ensuring no vaas are dropped when coming in and allows rolling restarts to upgrade versions.

### Proposal
Write a configuration example plugin that runs with multi-node listener

**Comment by JoeHowarth** [comment]
builds off https://github.com/wormhole-foundation/relayer-engine/issues/30

**Comment by gabzim** [comment]
Closing this since we no longer have a listener/executor process separation. Instead, what we will do is a remote wallet service.
