### ISSUE TITLE
Allow application wide prefix

### ISSUE THREAD

**Issue by gabzim** [wormhole-foundation/relayer-engine#41]
It's currently not possible to run more than one relayer engine application using redis as storage backend (eg. you can run one relayer engine with 2 plugins, but you can't run 2 relayer engines with 1 plugin each unless you provision a redis instance for each separately). It's common practice to namespace all redis keys with the name of the application (and allow said name to be customized), avoiding key collision and multi tenant setups on a shared redis.

**Comment by sebastianscatularo** [comment]
@gabzim @JoeHowarth I am closing this issue, feel free to re open it if you think there is something missing
