### ISSUE TITLE
Publish to NPM 

### ISSUE THREAD

**Issue by JoeHowarth** [wormhole-foundation/relayer-engine#50]
There should be 2 packages:
- @wormhole-foundation/relayer-engine [code link](https://github.com/wormhole-foundation/relayer-engine)
- @wormhole-foundation/relayer-plugin-interface [code link](https://github.com/wormhole-foundation/relayer-engine/tree/main/relayer-engine/packages/relayer-plugin-interface)

Ideally we could set it up so that when a new tag `vM.m.h` is added, a new npm release is rolled out, though this may not work with wormhole security posture

**Comment by kev1n-peters** [comment]
https://www.npmjs.com/package/@wormhole-foundation/relayer-engine
https://www.npmjs.com/package/@wormhole-foundation/relayer-plugin-interface
